# Generated by Django 5.0.6 on 2026-09-12 19:44

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import scheduling.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_enable_btree_gist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'confirmed')), expressions=[(scheduling.models.TsTzRange('start', 'end', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('host', '=')], name='no_overlapping_confirmed_bookings'),
        ),
    ]
